name: CI
on: [push]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "checking out branch ${{ github.ref }} on ${{ github.repository }}."
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install dependencies
        run: python -m pip install -r requirements.txt
      - name: perform unit testing
        run: \
          echo $PYTHONPATH
          ls
          python -m unittest
